export default function populateInventory() {
  const pop = [
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
  ];
  return pop;
}


function ppulateInventory() {
  const pop = [
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Mini',
      type: 'VW/VT',
      score: '5',
      price: '1000',
    },
    {
      manufacturer: 'Smoant',
      model: 'BattleStar',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1200',
    },
    {
      manufacturer: 'VooPoo',
      model: 'Drag',
      size: 'Full',
      type: 'VW/VT',
      score: '4',
      price: '1500',
    },
    {
      manufacturer: 'Joyetech',
      model: 'Evic',
      size: 'Mini',
      type: 'VW/VT',
      score: '2',
      price: '3420',
    },
    {
      manufacturer: 'Wismec',
      model: 'Reuleaux',
      size: 'Full',
      type: 'VW/TC',
      score: '3',
      price: '11500',
    },
    {
      manufacturer: 'Tesla',
      model: 'Punk',
      size: 'Full',
      type: 'VW/TC',
      score: '1',
      price: '12319',
    },
    {
      manufacturer: 'Sigelei',
      model: 'Fuchai',
      size: 'Nano',
      type: 'Squonk/VW',
      score: '2',
      price: '23121',
    },
    {
      manufacturer: 'Snowwolf',
      model: 'VFENG-S',
      size: 'Nano',
      type: 'VW/VT',
      score: '4',
      price: '23412',
    },
    {
      manufacturer: 'SMOK',
      model: 'Alien',
      size: 'Nano',
      type: 'TC',
      score: '2',
      price: '1500',
    },
  ];
  return pop;
}
